### ISSUE TITLE
Feature Request: add document for plateform

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/cwgo#117]
**Is your feature request related to a problem? Please describe.**

- plateform is not currently documented

**Describe the solution you'd like**

- add document for plateform

**Describe alternatives you've considered**

- None

**Additional context**

- None

**Comment by StellarisW** [comment]
WIP

**Comment by StellarisW** [comment]
Finished in https://github.com/cloudwego/cwgo/pull/130 and https://github.com/cloudwego/cloudwego.github.io/pull/906
