### ISSUE TITLE
Feature Request: support for template management for plateform

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/cwgo#118]
**Is your feature request related to a problem? Please describe.**

- not support for template management for plateform

**Describe the solution you'd like**

 - support for template management for plateform

**Describe alternatives you've considered**

- None

**Additional context**

- None

**Comment by StellarisW** [comment]
WIP

**Comment by StellarisW** [comment]
> WIP

in https://github.com/cloudwego/cwgo/pull/132
