### ISSUE TITLE
how to use go test command in different dictionary made by cwgo ?

### ISSUE THREAD

**Issue by fireapproval** [cloudwego/cwgo#120]
the quest follows:

i use cwgo generate a standard dictionary；then i create a go test file in `biz/dal` dictionary  to test if the mysql connection work,
but how can i change the environment of unit test, it always print error message of `panic: open conf/test/conf.yaml: no such file or directory`

**Comment by li-jin-gou** [comment]
same to https://github.com/cloudwego/cwgo/issues/29

**Comment by fireapproval** [comment]
> same to #29

thanks

**Comment by li-jin-gou** [comment]
> > same to #29
> 
> thanks

💖

**Comment by fireapproval** [comment]
if someone also have not solve this problem,you can see this blog article with address [kitex出现：open conf/test/conf.yaml: no such file or directory](https://blog.csdn.net/xwh3165037789/article/details/135130334?spm=1001.2014.3001.5502)
