### ISSUE TITLE
Is it a bug? if more than two arguments in a function of the .thrift file, the codes generated will be lack of commas.

### ISSUE THREAD

**Issue by lilhammer111** [cloudwego/cwgo#121]
![B80206DD@AA458649 3A04806500000000](https://github.com/cloudwego/cwgo/assets/113404700/3e03ac4f-d010-49e7-801a-0dd82b82522c)

**Comment by lilhammer111** [comment]
@fireapproval

**Comment by fireapproval** [comment]
some things also wrong happens in service dictionary which generated by `cwgo server --type RPC`  , the all unit test file lack symbol `,` in parameter of method
![Screenshot from 2023-12-18 16-44-30](https://github.com/cloudwego/cwgo/assets/125383416/9a7d31d7-2a57-4ad8-aa60-cb6ffc4e9956)

**Comment by li-jin-gou** [comment]
Thanks for the feedback, we'll fix it as soon as possible.

**Comment by li-jin-gou** [comment]
The problem should be that the case of multiple parameters is not handled correctly

**Comment by li-jin-gou** [comment]
cc @chaoranz758

**Comment by chaoranz758** [comment]
Can you provide the content of the thrift file and the commands to be executed when error occurs？ @lilhammer111
