### ISSUE TITLE
Feature Request: support for specifying repo owner of generating code repo

### ISSUE THREAD

**Issue by StellarisW** [cloudwego/cwgo#125]
**Is your feature request related to a problem? Please describe.**

- End user need to specify repo owner of generating code repo. Currently generating code repo owner is consistent with idl repo owner

- support for specifying repo owner of generating code repo

- None

![image](https://github.com/cloudwego/cwgo/assets/46246823/c6b42292-4959-41f1-9a91-01d619cfc9b8)
![image](https://github.com/cloudwego/cwgo/assets/46246823/a14743da-416a-436d-ba5d-0bc5aedd1d5c)

**Comment by li-jin-gou** [comment]
👍🏻
