### ISSUE TITLE
Feature Request: Give a more graceful error handling in platform

### ISSUE THREAD

**Issue by StellarisW** [cloudwego/cwgo#133]
**Is your feature request related to a problem? Please describe.**

currently, the platform code error handling is a little bit chaos, therefore it is difficult for end users to locate the source of errors from logs

**Describe the solution you'd like**

specify **error code** or **error type** for each error case, and print more detailed log (set appropriate log level) as much as possible.

**(also welcome providing alternative solutions)**

**Additional context**

**Comment by li-jin-gou** [comment]
❤️
