### ISSUE TITLE
cwgo doc 报错

### ISSUE THREAD

**Issue by darrenxyue** [cloudwego/cwgo#175]
idl文件是放到命令执行目录还是放到哪儿？
doc/dao 和 doc/model 目录都能生成，里面的代码生成不了，idl的位置尝试了很多都不行

**Comment by darrenxyue** [comment]
解决了，cwgo doc 需要依赖 protoc-gen-go，我等会儿去文档上提交一下

**Comment by darrenxyue** [comment]
你们直接加一下吧，https://www.cloudwego.io/zh/docs/cwgo/getting-started/这个页面

**Comment by StellarisW** [comment]
> 你们直接加一下吧，[这个页面](https://www.cloudwego.io/zh/docs/cwgo/getting-started/) go install github.com/golang/protobuf/protoc-gen-go

好的，感谢
