### ISSUE TITLE
cwgo 生成 handler 代码

### ISSUE THREAD

**Issue by darrenxyue** [cloudwego/cwgo#189]
这个错误码没有很好的遵循 HTTP status & RESTful API 规范，正常来说 client 侧不符合预期应该是 4xx 错误吗、服务端处理错误为 5xx，这里可以修改下吗？
<img width="604" alt="image" src="https://github.com/cloudwego/cwgo/assets/28799116/395d7509-c65b-4958-ab94-bc8f3d710140">

**Comment by li-jin-gou** [comment]
使用自定义模版吧自己实现一个模版吧，现在这个模版修改了可能对用户造成影响，有风险。

**Comment by darrenxyue** [comment]
猜到会这么回答了，算了，还是用 gin 吧

**Comment by li-jin-gou** [comment]
其实如果你用 gin 没有脚手架的话，和纯用 hertz 的框架没啥区别，区别就在脚手架上。

**Comment by li-jin-gou** [comment]
@darrenxyue 新增了一个 V2 模版。https://github.com/yuxialuozi/standard_v2/blob/main/biz/handler/hello3/hello_service.go#L20
