### ISSUE TITLE
--sql_dir参数 不生效

### ISSUE THREAD

**Issue by leebiq** [cloudwego/cwgo#192]
![image](https://github.com/cloudwego/cwgo/assets/89843003/049df635-0aa6-420d-9836-dc2664f2012e)
这个地方的文档说使用 --sql_dir 参数之后 --dsn 参数就会失效，
但是发现通过  go install github.com/cloudwego/cwgo@latest 安装的cwgo，不支持这个能力

cwgo  model --db_type mysql --unittest true --nullable true --type_tag true --sql_dir deploy/sql/ 这个是执行的命令

然后就会报错：
[error] failed to initialize database, got error dial tcp 127.0.0.1:3306: connect: connection refused
go/pkg/mod/github.com/cloudwego/cwgo@v0.1.0/cwgo.go:47: dial tcp 127.0.0.1:3306: connect: connection refused

然后发现应该 v0.1.0 这个版本的代码跟master的代码不一样，你们是不是需要重新生成一个版本了？

**Comment by li-jin-gou** [comment]
抱歉，还没有发版，我们近期会发版 @leebiq

**Comment by li-jin-gou** [comment]
发版了 @leebiq
