### ISSUE TITLE
cwgo mode 生成的DB model code时， 指定 --type_tag 和 --index_tag 参数不生效

### ISSUE THREAD

**Issue by xuanskyer** [cloudwego/cwgo#199]
**Describe the bug**

cwgo mode 生成的DB model code时， 指定 --type_tag 和 --index_tag 参数不生效
运行命令：`cwgo  model  --db_type mysql --dsn "root:@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=true&loc=Local" --type_tag true --index_tag true`

生成的model目录下的 xx.gen.go 文件中，没有type 和index 的关键字标签

**To Reproduce**

1. 运行命令：`cwgo  model  --db_type mysql --dsn "root:@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=true&loc=Local" --type_tag true --index_tag true` 

**Expected behavior**

可以正确生成type 和index 标签

**Screenshots**

<img width="1207" alt="image" src="https://github.com/user-attachments/assets/9648b1ee-be0c-426b-922e-ef3708e52dde">

**Kitex version:**

v0.6.1

**Environment:**
```
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/rocx/Library/Caches/go-build"
GOENV="/Users/rocx/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/rocx/projects/gopath/pkg/mod"
GOOS="darwin"
GOPATH="//Users/rocx/projects/gopath"
GOPROXY="https://proxy.golang.com.cn,direct"
GOROOT="/usr/local/go1.20"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go1.20/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/rocx/projects/gopath/src/cwgo-0.1.1/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7g/r8fjwdq52xsffxndf32jksq40000gn/T/go-build1139145619=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
**Additional context**

**Comment by li-jin-gou** [comment]
修复了
