### ISSUE TITLE
生成 DB 时，--type_tag命令字段无效

### ISSUE THREAD

**Issue by AdrianWangs** [cloudwego/cwgo#203]
当我运行了如下命令

![QQ_1722402250246](https://github.com/user-attachments/assets/5fd150a7-4514-4c55-bb2c-52c576439599)

最后生成的 model 文件中，并没有包含数据类型的标记：

![QQ_1722402483557](https://github.com/user-attachments/assets/81296032-4be6-4aee-b385-53004a669eeb)

**Comment by Skyenought** [comment]
你应该直接指定 --type_tag, 并不需要指定它为 true

**Comment by AdrianWangs** [comment]
不行，即使不指定为 true，依然无法生成数据类型 tag：

![QQ_1722591078784](https://github.com/user-attachments/assets/5bcf6833-fba0-4466-8ec7-164d7f72c280)
