### ISSUE TITLE
生成 DB 时，--type_tag命令字段无效

### ISSUE THREAD

**Issue by AdrianWangs** [cloudwego/cwgo#205]
你应该直接指定 --type_tag, 并不需要指定它为 true

_Originally posted by @Skyenought in https://github.com/cloudwego/cwgo/issues/203#issuecomment-2264955674_
            
即使不指定为 true，也无法生成数据类型字段：

![QQ_1722591078784](https://github.com/user-attachments/assets/6932aa71-879a-4dff-81c8-6d395988df4c)

**Comment by yuxialuozi** [comment]
hello，感觉是你这边的问题。这个问题后面已经修复了，你是不是没有更新到最新版本。
![QQ_1722914917694](https://github.com/user-attachments/assets/7b468173-ddf8-43f6-9263-6a61a8181a35)

**Comment by AdrianWangs** [comment]
> hello，感觉是你这边的问题。这个问题后面已经修复了，你是不是没有更新到最新版本。 ![QQ_1722914917694](https://private-user-images.githubusercontent.com/139631989/355301658-7b468173-ddf8-43f6-9263-6a61a8181a35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Mzk2NTYsIm5iZiI6MTcyMjkzOTM1NiwicGF0aCI6Ii8xMzk2MzE5ODkvMzU1MzAxNjU4LTdiNDY4MTczLWRkZjgtNDNmNi05MjYzLTZhNjFhODE4MWEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMDE1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTNhY2JjMWE1OGFiNDc2YjI4MWViZDM1ODJkYzUzMDY1ZWQwYzRhYWRjOGFlZDY3ZGZlZDVkZTY2MzFmZjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xROUxom8StgOVWrochj8DbjIn_FrBCPhWUbn9NvuJP4)

不好意思，我刚刚去查看了一下，确实是没有升级到最新版本，最新版本已经解决了，谢谢，辛苦了
