### ISSUE TITLE
在非gopath下使用cwgo命令添加-module失效

### ISSUE THREAD

**Issue by nanakura** [cloudwego/cwgo#24]
**Describe the bug**

在非gopath下使用cwgo命令添加-module失效

**To Reproduce**

1. mkdir cwgo_test && cd cwgo_test
2. go mod init cwgo_test
3. 添加idl
4. 輸入`cwgo server .....`的命令

**Expected behavior**

生成成功

**Screenshots**

![image](https://user-images.githubusercontent.com/69560752/213429409-4c806f9c-63df-4dd2-9465-b4c2b3738f4a.png)

**Kitex version:**

v0.4.4

**Environment:**

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/acs/.cache/go-build"
GOENV="/home/acs/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/acs/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/acs/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/snap/go/10030"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/10030/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/acs/workspace/projects/cwgo_test/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3863773717=/tmp/go-build -gno-record-gcc-switches"

**Additional context**
none

**Comment by Duslia** [comment]
done. You can use the latest branch.
