### ISSUE TITLE
proposal: add the-clean-architecture layout template

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/cwgo#26]
**Is your feature request related to a problem? Please describe.**

Currently there is only one MVC  layout template and need to add   the-clean-architecture layout template

**Describe the solution you'd like**

refer to https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html and add template

**Additional context**

- https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html

**Comment by StellarisW** [comment]
seconded !
we could add "--layout_type" option in `server` command to support various layout templates

**Comment by li-jin-gou** [comment]
add wire
