### ISSUE TITLE
cwgo 依然不支持windows吗？

### ISSUE THREAD

**Issue by sishui** [cloudwego/cwgo#27]
如题

**Comment by Duslia** [comment]
目前还不支持，windows 可以使用 wsl，我们也会尽快优化

**Comment by sishui** [comment]
另外我在wsl下，用`go install `安装了cwgo，并执行`cwgo init` 执行
![1675073808465](https://user-images.githubusercontent.com/1058519/215449700-ff1b3e24-7105-4462-a265-9945fd3b30c7.png)
出现此错误

我如文档的动图所示，不输入module, 也会出现相同错误，这个要如何解决

**Comment by li-jin-gou** [comment]
我们看下，感谢反馈.

**Comment by welkeyever** [comment]
由于 [kitex 尚未完成 windows 环境适配](https://github.com/cloudwego/kitex/issues/766)，因此涉及到生成 kitex 项目的部分，目前还是不支持 windows；

hertz 已经完成 windows 适配了，cwgo 针对 hertz 部分预期是支持 windows的，欢迎尝试，有任何问题也欢迎随时抛出来~

有关 kitex 支持 windows 的问题也欢迎直接到 https://github.com/cloudwego/kitex/issues/766 这个 issue 下面进行互动~
