### ISSUE TITLE
获取conf路径的问题

### ISSUE THREAD

**Issue by baodingfengyun** [cloudwego/cwgo#29]
**Describe the bug**

(1) 正常运行main.go时, 与conf处于同一目录层级. 能获取正常的配置文件conf/test/conf.yaml
(2) 在biz/service/xx_test.go 里面进行初始化的时候, 不能获取正确的conf/test/conf.yaml路径

需要在initConf里面动态获取配置文件的路径
func initConf() {
  wd, _ := os.Getwd()
  wd = strutil.Before(wd, "cw_test")
  // 获取绝对路径
  prefix := wd + "cw_test/conf"
  ...

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kitex version:**

Please provide the version of Kitex you are using.

**Environment:**

The output of `go env`.

**Additional context**

**Comment by StellarisW** [comment]
可以考虑在运行test文件的时候，执行路径设置为与main.go同级，
感觉没有必要再写另外的代码，
当然如果有必要的话，比较好的方法是通过 `go list -json -m` 命令获取 `dir`命令的值，即 `main.go` 所处的绝对路径

**Comment by fireapproval** [comment]
if someone also have not solve this problem,you can see this blog article with address [kitex出现：open conf/test/conf.yaml: no such file or directory](https://blog.csdn.net/xwh3165037789/article/details/135130334?spm=1001.2014.3001.5502)

**Comment by li-jin-gou** [comment]
thanks



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月21日(周四) 下午4:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [cloudwego/cwgo] 获取conf路径的问题




 
if someone also have not solve this problem,you can see this blog article with address kitex出现：open conf/test/conf.yaml: no such file or directory
