### ISSUE TITLE
更新proto 参数，重新生成代码不生效

### ISSUE THREAD

**Issue by gumap** [cloudwego/cwgo#47]
**Describe the bug**

在proto中定义rpc方法，当参数变动时，再次调用
```
cwgo server -serverice=myservice -type RPC -idl=idl/myservice.proto -modelu test/myservice
```
没有生成新的struct

kitex：v0.5.0
cwgo: v0.0.1
go: v1.20.2

**Comment by FGYFFFF** [comment]
改变方法的参数了吗？ idl 里建议不要修改 method 的请求/返回参数

**Comment by gumap** [comment]
用kitex,重新生成下就变过来了，但是idl里修改请求返回的结构体是不了避免的

**Comment by gumap** [comment]
![image](https://user-images.githubusercontent.com/125720881/224199830-160235e5-b563-44c1-8ec2-49bd00013ef6.png)
![image](https://user-images.githubusercontent.com/125720881/224199948-745405b8-1d5c-478b-9256-e71ff5ced93f.png)
下面是我修改的返回结构，输入命令但是不起作用

**Comment by FGYFFFF** [comment]
cc @Duslia 
不过看起来是你的

**Comment by Duslia** [comment]
只检查函数名，不会检查入参和返回值

**Comment by Duslia** [comment]
我们后面优化一下，如果你有兴趣的话，也欢迎提 pr

**Comment by gumap** [comment]
> 只检查函数名，不会检查入参和返回值

了解
