### ISSUE TITLE
Proposal: provide both rpc & http APIs in one server

### ISSUE THREAD

**Issue by welkeyever** [cloudwego/cwgo#60]
**Describe the solution you'd like**
cwgo provide a way for providing both rpc & http APIs in one server.

**Describe alternatives you've considered**
Organically combine kitex and hertz to distribute different protocol processing logic through protocol sniffing at the protocol layer.
Users generates a server that supports different protocols at the same time through a set of IDL.

**Additional context**
No extra copy during the entire process.

**Comment by zgaaaa** [comment]
It is recommended to form a unified directory structure for rpc and http, so that switching from a single architecture to microservices will become easier, similar to go-zero

**Comment by welkeyever** [comment]
@zgaaaa Good idea, the templates of hertz/kitex have already done it - if there is  issue with that, you may probably launch another issue to describe about - this issue is mainly used to track the protocol sniffing things.

**Comment by li-jin-gou** [comment]
already support
