### ISSUE TITLE
cwgo使用问题

### ISSUE THREAD

**Issue by R2coding2run** [cloudwego/cwgo#64]
cwgo目前模版 生成biz/service 存在问题如下：
1）list getDemo(1:i64 entID , 2:i64 userID , 3:byte clientType),
生成 thrift entIDint64userID
中间没有","分隔
2 生成 test 对于 int string 类型
生成代码为 &int64{}
这是 go语言不支持的语法
3）生成rpc客户端
对于返回结果为 string的客户端
demo_default.go
if err != nil {
klog.CtxErrorf(ctx, "UpdateApp call failed,err =%+v", err)
return nil, err
}
永远是return nil, err，实际需要为 return "",nil

**Comment by li-jin-gou** [comment]
方便详细描述一下嘛？ 1 和 2 看起来是 kitex_gen 生成的代码问题还是？？

**Comment by R2coding2run** [comment]
cwgo生成biz/service的模版问题 service.yaml  41行  改为   func (s *{{.Name}}Service) Run({{range .Args}}{{LowerFirst .Name}} {{.Type}},{{end}}) error {
51行  func (s *{{.Name}}Service) Run({{range .Args}}{{LowerFirst .Name}} {{.Type}},{{end}}) (resp {{.Resp.Type}}, err error) {
