### ISSUE TITLE
5.15 cwgo 更新命名规则 等

### ISSUE THREAD

**Issue by R2coding2run** [cloudwego/cwgo#67]
cwgo之前版本可不可以 打一个tag

**Comment by li-jin-gou** [comment]
由于 https://github.com/cloudwego/hertz/pull/660  修复了一个问题，导致中间件命名规则发生了变化，你可以先使用 go install ***@coomitID 的方式用旧的 cwgo.

**Comment by li-jin-gou** [comment]
近期打一下 tag
