### ISSUE TITLE
question[hertz]: default error code

### ISSUE THREAD

**Issue by rogerogers** [cloudwego/cwgo#82]
https://github.com/cloudwego/cwgo/blob/005171258a17b86d6ede65315bf52b29dde06578/tpl/hertz/server/standard/package.yaml#L30-L46

Should "bind error" be the default status code 400, and should "service error" be the default 500?

**Comment by li-jin-gou** [comment]
Currently encountered a lot of internal practices are uniformly return 200, and then use the business status code to control the reporting of errors.

**Comment by rogerogers** [comment]
Got it, thanks
