### ISSUE TITLE
It is inappropriate to rely on go after building

### ISSUE THREAD

**Issue by rogerogers** [cloudwego/cwgo#95]
**Describe the bug**

This method gets the path dependent on the go binary
https://github.com/cloudwego/cwgo/blame/44092d34148e073aaaf9c1ad3a22d79c098ec44d/tpl/hertz/server/standard/layout.yaml#L201

**To Reproduce**

eg dockerfile below

https://github.com/bnkamalesh/golang-dockerfile/blob/master/Dockerfile-alpine 

In order to reduce the size of the docker image, it is generally built using the go image and then run using the ordinary alpine image. Relying on go will cause panic.

**Expected behavior**

**Screenshots**

**Kitex version:**

Please provide the version of Kitex you are using.

**Environment:**

The output of `go env`.

**Additional context**

**Comment by li-jin-gou** [comment]
@chaoranz758
